name: Auto-Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Server
        run: |
          sshpass -p '${{ vars.DEPLOY_HOST }}' ssh -o StrictHostKeyChecking=no -p ${{ vars.DEPLOY_PORT }} '${{ vars.DEPLOY_USERNAME }}@${{ vars.DEPLOY_HOST }}' <<EOF
          cd '${{ vars.DEPLOY_PATH }}'

          # public repo
          git pull https://github.com/tauseedzaman/connectme.git

          php artisan migrate
          php artisan config:clear
          php artisan route:clear
          php artisan view:clear
          php artisan cache:clear
          php artisan event:clear
          EOF
